#!/bin/bash

TMPDIR=/tmp/.pkgcnv
TMPFILE=/tmp/.pkgcnvf
tl=`pwd`

for fn in $*; do
	rm -rf $TMPDIR;
	mkdir -p $TMPDIR;
	echo "Converting $fn"
	cd $TMPDIR
	tar zxvf $tl/$fn | grep -v '^.PKGINFO' | grep -v '._install' >$TMPFILE
	mv $TMPFILE ./.FILELIST
	if [ -f ._install ]; then
		tar cfz /new/$fn .PKGINFO .FILELIST ._install *
	else
		tar cfz /new/$fn .PKGINFO .FILELIST *
	fi
done
